---
title: "Many Drugs at Once"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```


```{r load in}
library(dplyr)
library(EnsDb.Hsapiens.v79)

x = list.files(path = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/Drug DEGs High")


genes_in_model <- openxlsx::read.xlsx("C:/Users/cmoor/Documents/Papin Lab/Human1/Human-GEM.xlsx", sheet = 4)

ENSEMBLinmodel = as.data.frame(genes_in_model[,2])
colnames(ENSEMBLinmodel) = "GeneID"



for (i in 1:length(x)){
  DrugDat = read.table(file = paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/Drug DEGs High/", x[i]), sep = ',', header = TRUE)

  DrugDat = DrugDat[grep("Open TG-GATEs Human", DrugDat$Dataset),]
  DrugDat = DrugDat[grep("High", DrugDat$Dose),]
  DrugDat = DrugDat[grep("24", DrugDat$Time),]
  
  geneSymbols = DrugDat$Gene
  
  geneIDs2 <- ensembldb::select(EnsDb.Hsapiens.v79, keys= geneSymbols, keytype = "SYMBOL", columns = c("SYMBOL","GENEID"))

  geneIDs2 = geneIDs2[-grep("LRG", geneIDs2$GENEID),]
  colnames(geneIDs2) = c("Gene","GeneID")

  DrugDatWithGenes = inner_join(DrugDat, geneIDs2, by = "Gene")
  
  
  DrugDatModelGenes = inner_join(DrugDatWithGenes, ENSEMBLinmodel, by = "GeneID")

  DrugDatModelGenes$log2.fold.change.[DrugDatModelGenes$FDR > 0.1] = 0

  colnames(DrugDatModelGenes) = c("Gene", "logFC", "P.value", "adj.P.Val", "Dataset", "Dose", "Time", "NAME")



  write.table(DrugDatModelGenes, file = paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/SaveDEGs/", x[i]), 
            col.names = TRUE, row.names = FALSE, sep = ",")
}
```


```{r Drug Sig}

options(java.parameters = "-Xmx1024m")

library(dplyr)
library(ggplot2)
library(xlsx)
library(tidyr)
library(scales)
library(ggplot2)
library(randomForest)
library(readxl)

library(grid)
library(gridExtra)
library(lattice)
library(ggpubr)
library(cowplot)
library(forcats)

library(ggnewscale)



x = list.files(path = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugTides")

allGenes = x[grep("allGenes", x)]
random = x[grep("random", x)]

for(i in 1:length(random)){
  ischemic.random <- readxl::read_xlsx(path= paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugTides/", random[i]), 
                                     sheet = 1, 
                                     col_names = FALSE)
  
  colnames(ischemic.random)[1:1000] <- paste0('X',c(1:1000))
    
  # colnames are 1:1000
  # Need to read in some example task data for task names
  GSE5406.Ischemic = read.xlsx(file = paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugTides/", allGenes[i]), sheetIndex = 1, header = 0)
  colnames(GSE5406.Ischemic) = c('ID','description','taskScore','significance')
  
  write.xlsx(GSE5406.Ischemic, file = paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig/", "PVal_", allGenes[i]))
  
  ischemic.random <- cbind(GSE5406.Ischemic %>% dplyr::select(ID, description), ischemic.random)
  
  # Pick out the TIDEs from GSE5406
  GSE5406.Ischemic <- GSE5406.Ischemic %>% 
    mutate(significance = ifelse(abs(significance) > 0.025, 0, ifelse(significance < 0, -1, 1))) %>% 
    dplyr::select(ID, description, taskScore, significance)
  
  
  write.xlsx(GSE5406.Ischemic, file = paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig/", "SignificantTasks", allGenes[i]))
  i
}


```

```{r OneSigXL}
library(readxl)
library(xlsx)

x = list.files(path = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig", full.names = T)

Sig = x[grep("SignificantTasks", x)]

DrugSigMat =  read.xlsx(file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig/SignificantTasksAll_allGenes.xlsx", sheetIndex = 1, header = 1)


DrugNames = colnames(DrugSigMat)[2:length(colnames(DrugSigMat))]

DrugNames = gsub(".", " ", DrugNames, fixed = T)

for(i in 1:length(DrugNames)){
  
  DrugSig = read.xlsx(file = Sig[grep(substr(DrugNames[i], 1, 10), Sig, ignore.case = T)], sheetIndex = 1, header = 1)
  DrugSigMat[,i+1] = DrugSig$significance
  
}

write.xlsx(DrugSigMat, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig/DrugMatSigFilledIn.xlsx", row.names = F)

```

```{r Combine}
library(readxl)
library(xlsx)

x = list.files(path = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugTides")

allGenes = x[grep("allGenes", x)]
random = x[grep("random", x)]

SigMat = data.frame(matrix(NA, nrow = 135, ncol = length(allGenes)))
TaskMat = data.frame(matrix(NA, nrow = 135, ncol = length(allGenes)))

for(i in 1:length(allGenes)){
  Sig = read.xlsx(file = paste0("C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig/", "PVal_", allGenes[i]), sheetIndex = 1, header = 1)
  Sig$significance[Sig$significance == 0] = .001
  
  SigMat[,i] = Sig$significance
  TaskMat[,i] = Sig$taskScore
}

allGenesNames = gsub("High_allGenes.xlsx", "", allGenes)


colnames(SigMat) = allGenesNames
rownames(SigMat) = Sig$description

colnames(TaskMat) = allGenesNames
rownames(TaskMat) = Sig$description

AbsMat = log10(abs(SigMat))

for(i in 1:ncol(AbsMat)){
  AbsMat[SigMat[,i] > 0,i] = -AbsMat[SigMat[,i] > 0,i]

}

#write.xlsx(TaskMat, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugSig/TaskMat.xlsx", row.names = T)
```



```{r Heatmap}
library(tidyr)
library(ggplot2)

StatMat = stack(AbsMat)
TaskStack = stack(TaskMat)
Subsys = as.vector(t(rbind(rownames(AbsMat),rownames(AbsMat),rownames(AbsMat))))


Names = read.xlsx(file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugNames.xlsx", sheetIndex = 1, header = 0)

for(i in 1:nrow(Names)){
  
  TaskStack$ind = gsub(Names[i,1],Names[i,2], TaskStack$ind)
  
}

TaskStack$ind = as.factor(TaskStack$ind)

for(i in 1:5){
  
  Subsys = cbind(Subsys, Subsys)
  
}

Subsys = Subsys[1:nrow(StatMat)]

StatMat$Subsys = Subsys
TaskStack$Subsys = Subsys

library("ggdendro")

otter_matrix <- t(as.matrix(AbsMat))
rownames(otter_matrix) <- colnames(AbsMat)


otter_dendro <- as.dendrogram(hclust(d = dist(x = otter_matrix, method = "euclidean"), method = "ward.D2"))
dendro_plot <- ggdendrogram(data = otter_dendro, rotate = F)
dendro_plot <- dendro_plot + theme(axis.text.x = element_text(size = 8))

otter_order <- order.dendrogram(otter_dendro)

TaskStack$ind <- factor(x = TaskStack$ind,
                               levels = unique(TaskStack$ind)[otter_order], 
                               ordered = TRUE)

png(file="C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugHeatmap.png",
width=1100, height=900)
ggplot(TaskStack, aes(ind, Subsys, fill= values)) + 
  geom_tile() +
  scale_fill_gradient2('Task Score', low = "blue", mid = "white", high = "red", midpoint = 0, guide = guide_colorbar(title.position = "top", frame.colour = "black", ticks.colour = "black")) +
  theme(axis.text.y = element_text(size = 8)) +
  theme(axis.text.x = element_text(size = 8)) +
  coord_flip() +
  geom_tile(color = "black", size = .01) +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=10)) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")
dev.off()

# Preview the plot
png(file="C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugDendro.png",
width=1100, height=900)
print(dendro_plot)
dev.off()

hc = hclust(dist(x = otter_matrix, method = "euclidean"), method = "ward.D2")
plot(hc, hang = -3, cex = 0.1)


hc2 = as.dendrogram(hc)
otter_order <- order.dendrogram(hc2)


otter_matrix <- t(as.matrix(AbsMat))
hcDrug = hclust(dist(x = otter_matrix, method = "euclidean"), method = "ward.D2")
plot(hcDrug, hang = -3, cex = 0.1)


hc2Drug = as.dendrogram(hcDrug)
otter_orderDrug <- order.dendrogram(hc2Drug)



StatMat$Subsys <- factor(x = StatMat$Subsys,
                               levels = StatMat$Subsys[otter_order], 
                               ordered = TRUE)
library(gplots)
heatmap(as.matrix(AbsMat))


otter_matrix <- as.matrix(TaskMat)
rownames(otter_matrix) <- rownames(TaskMat)

library(dendextend)
otter_dendro <- as.dendrogram(hclust(d = dist(x = otter_matrix, method = "euclidean"), method = "ward.D2"))
dendro_plot <- ggdendrogram(data = otter_dendro, rotate = F)
dendro_plot <- dendro_plot + theme(axis.text.x = element_text(size = 9))

plot(dendro_plot)


otter_matrix <- as.matrix(AbsMat)
rownames(otter_matrix) <- rownames(AbsMat) 

otter_dendro <- as.dendrogram(hclust(d = dist(x = otter_matrix, method = "euclidean"), method = "ward.D2"))
dendro_plot <- ggdendrogram(data = otter_dendro, rotate = F)
dendro_plot <- dendro_plot + theme(axis.text.x = element_text(size = 8))
plot(dendro_plot)

png(file="C:/Users/cmoor/Documents/Papin Lab/Human1/Drug Treatment/DrugHeatmapBig.png",
width=5000, height=2000)
heatmap.2(t(as.matrix(TaskMat)), trace = "none", keysize = .1)
dev.off()

#write.xlsx(StatMat, file = "C:/Users/cmoor/Documents/Class/BME 6311/HeatMapSig.xlsx")



ggplot(StatMat, aes(ind, Subsys, fill= values)) + 
  geom_tile() +
  scale_fill_gradient2('-log10 p-value', low = "blue", mid = "white", high = "red", midpoint = 0, guide = guide_colorbar(title.position = "top", frame.colour = "black", ticks.colour = "black")) +
  theme(axis.text.y = element_text(size = 14)) +
  theme(axis.text.x = element_text(size = 10)) +
  coord_flip() +
  geom_tile(color = "black", size = .01) +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  theme(axis.text.y = element_text(angle = 90, vjust = .0, hjust=.5)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=10)) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center") +
  theme(legend.position="none")



ggplot(StatMat, aes(ind, Subsys, fill= values)) + 
  geom_tile() +
  scale_fill_gradient2('-log10 p-value', low = "#00a873", mid = "white", high = "#e04102", midpoint = 0, guide = guide_colorbar(title.position = "top", frame.colour = "black", ticks.colour = "black")) +
  theme(axis.text.y = element_text(size = 1)) +
  theme(axis.text.x = element_text(size = 1)) +
  coord_flip() +
  geom_tile(color = "black", size = .01) +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  #theme(axis.text.y = element_text(angle = 90, vjust = .0, hjust=.5)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=10)) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")






```

```{r specific tasks}



idx = grep("Androgen metabolism|Ether lipid metabolism|Glucocorticoid biosynthesis|Tryptophan metabolism|Xenobiotics metabolism|Serotonin and melatonin biosynthesis|Pentose and glucuronate interconversions|Vitamin A metabolism", TaskStack$Subsys)

TaskStackLiverTask = TaskStack[idx,]
  
png(file="C:/Users/cmoor/Documents/Papin Lab/Admin/2022-5-31 Draft/LiverTasksHeatmapRevised2.png",
width=600, height=900)
ggplot(TaskStackLiverTask, aes(ind, Subsys, fill= cut(values,breaks = seq(from = -2, to = 2, length.out = 12), labels = seq(from = -2, to = 2, length.out = 11)))) + 
  geom_tile() +
  scale_fill_manual(drop = F, values = c("#010a6e","#0013e3","#606ced","#949cf3","#c1c6f8","white","#fbd5d5","#f8b8b8","#f06b6b","#e60202","#700101"), name = "Task Score")+
  theme(axis.text.y = element_text(size = 12)) +
  theme(axis.text.x = element_text(size = 16, face = "bold")) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  #theme(axis.text.y = element_text(angle = 90, vjust = .0, hjust=.5)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=10, face = "bold")) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())
dev.off()




idx = grep("fatty acid|lipid|linoleate|Eicosanoid metabolism|Arachidonic acid", TaskStack$Subsys, ignore.case = T)

TaskStackLipidTask = TaskStack[idx,]


ggplot(TaskStackLipidTask, aes(ind, Subsys, fill= values)) + 
  geom_tile() +
  scale_fill_gradient2('Task Score', low = "blue", mid = "white", high = "red", midpoint = 0, guide = guide_colorbar(title.position = "top", frame.colour = "black", ticks.colour = "black")) +
  theme(axis.text.y = element_text(size = 14)) +
  theme(axis.text.x = element_text(size = 16, face = "bold")) +
  coord_flip() +
  geom_tile(color = "black", size = .01) +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  #theme(axis.text.y = element_text(angle = 90, vjust = .0, hjust=.5)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=10)) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")


png(file="C:/Users/cmoor/Documents/Papin Lab/Admin/2022-5-31 Draft/LipidTasksHeatmapRevised.png",
width=1100, height=1300)
ggplot(TaskStackLipidTask, aes(ind, Subsys, fill= cut(values,breaks = seq(from = -2.5, to = 2.5, length.out = 12), labels = seq(from = -2.5, to = 2.5, length.out = 11)))) + 
  geom_tile() +
  scale_fill_manual(drop = F, values = c("#010a6e","#0013e3","#606ced","#949cf3","#c1c6f8","white","#fbd5d5","#f8b8b8","#f06b6b","#e60202","#700101"), name = "Task Score")+
  theme(axis.text.y = element_text(size = 12)) +
  theme(axis.text.x = element_text(size = 16, face = "bold")) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  #theme(axis.text.y = element_text(angle = 90, vjust = .0, hjust=.5)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(1, 'cm'), #change legend key size
        legend.key.height = unit(1, 'cm'), #change legend key height
        legend.key.width = unit(1, 'cm'), #change legend key width
        legend.title = element_text(size=14), #change legend title font size
        legend.text = element_text(size=10, face = "bold")) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())
dev.off()



TaskStackLipidTask$Subsys = gsub("metabolism","met.", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("poly-unsaturated fatty acid","PUFA", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("unsaturated fatty acid","UFA", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("fatty acid","FA", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("mitochondrial","mito.", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("peroxisomal","perox.", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("endoplasmic reticular","ER", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("cytosolic","ctyo.", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("peroxisomal","perox.", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("beta oxidation","β Oxi.", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("lacto and neolacto series","lacto", TaskStackLipidTask$Subsys, ignore.case = T)
TaskStackLipidTask$Subsys = gsub("series","", TaskStackLipidTask$Subsys, ignore.case = T)


ggplot(TaskStackLipidTask, aes(ind, Subsys, fill= cut(-values,breaks = seq(from = 2.5, to = -2.5, length.out = 12), labels = seq(from = 2.5, to = -2.5, length.out = 11)))) + 
  geom_tile() +
  scale_fill_manual(drop = F, values = c("#700101","#e60202","#f06b6b","#f8b8b8","#fbd5d5","white","#c1c6f8","#949cf3","#606ced","#0013e3","#010a6e"), name = "Task Score")+
  theme(axis.text.y = element_text(size = 8, face = "bold")) +
  theme(axis.text.x = element_text(size = 10, face = "bold")) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(.5, 'cm'), #change legend key size
        legend.key.height = unit(.5, 'cm'), #change legend key height
        legend.key.width = unit(.5, 'cm'), #change legend key width
        legend.title = element_text(size=14, face= "bold"), #change legend title font size
        legend.text = element_text(size=10, face = "bold")) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())




TaskStackLiverTask$Subsys = gsub("metabolism","met.", TaskStackLiverTask$Subsys, ignore.case = T)
TaskStackLiverTask$Subsys = gsub("interconversions","met.", TaskStackLiverTask$Subsys, ignore.case = T)
TaskStackLiverTask$Subsys = gsub("biosynthesis","synth.", TaskStackLiverTask$Subsys, ignore.case = T)



ggplot(TaskStackLiverTask, aes(Subsys, ind, fill= cut(-values,breaks = seq(from = 2.5, to = -2.5, length.out = 12), labels = seq(from = 2.5, to = -2.5, length.out = 11)))) + 
  geom_tile() +
  scale_fill_manual(drop = F, values = c("#700101","#e60202","#f06b6b","#f8b8b8","#fbd5d5","white","#c1c6f8","#949cf3","#606ced","#0013e3","#010a6e"), name = "Task Score")+
  theme(axis.text.y = element_text(size = 8, face = "bold")) +
  theme(axis.text.x = element_text(size = 10, face = "bold")) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, vjust = .35, hjust=1)) +
  theme(axis.title.x=element_blank(),axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold")) +
  theme(legend.key.size = unit(.5, 'cm'), #change legend key size
        legend.key.height = unit(.5, 'cm'), #change legend key height
        legend.key.width = unit(.5, 'cm'), #change legend key width
        legend.title = element_text(size=14, face= "bold"), #change legend title font size
        legend.text = element_text(size=10, face = "bold")) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())



level_order <- c('Vitamin A met.', 'Pentose and glucuronate met.', 'Serotonin and melatonin synth.', 'Xenobiotics met.', 'Tryptophan met.', 'Glucocorticoid synth.', 'Ether lipid met.', 'Androgen met.')



ggplot(TaskStackLiverTask, aes(Subsys, ind, fill= cut(-values,breaks = seq(from = 2.5, to = -2.5, length.out = 12), labels = seq(from = 2.5, to = -2.5, length.out = 11)))) + 
  geom_tile() +
  scale_fill_manual(drop = F, values = c("#700101","#e60202","#f06b6b","#f8b8b8","#fbd5d5","white","#c1c6f8","#949cf3","#606ced","#0013e3","#010a6e"), name = "Task Score")+
  theme(axis.text.y = element_text(size = 8, face = "bold")) +
  theme(axis.text.x = element_text(size = 10, face = "bold")) +
  coord_flip() +
  theme(axis.text.x=element_blank(), legend.position="none") +
  theme(axis.title.y=element_blank(),axis.ticks = element_blank()) +
  theme(axis.text.y = element_text(face="bold", size = 18)) +
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank()) + xlab("Subsystems") + ylab("Drugs") +ggtitle("Treatment Difference Task Scores")+
  theme(axis.text = element_text(size = 26)) +
  theme(axis.title = element_text(size = 26, face = "bold")) +
  theme(plot.title = element_text(size = 26,face = "bold"))

ggplot(TaskStackLiverTask, aes(factor(Subsys, level = level_order), ind, fill= cut(-values,breaks = seq(from = 2.5, to = -2.5, length.out = 12), labels = seq(from = 2.5, to = -2.5, length.out = 11)))) + 
  geom_tile() +
  scale_fill_manual(drop = F, values = c("#700101","#e60202","#f06b6b","#f8b8b8","#fbd5d5","white","#c1c6f8","#949cf3","#606ced","#0013e3","#010a6e"), name = "Task Score")+
  theme(axis.text.y = element_text(size = 8, face = "bold")) +
  theme(axis.text.x = element_text(size = 10, face = "bold")) +
  coord_flip() +
  theme(axis.text.x=element_blank(), legend.position="none") +
  theme(axis.title.y=element_blank()) +
  theme(axis.text.y = element_text(face="bold", size = 18)) +
  theme(axis.ticks.y = element_blank())+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank()) + xlab("Subsystems") + ylab("Drugs") +ggtitle("Treatment Difference Task Scores")+
  theme(axis.text = element_text(size = 26)) +
  theme(axis.title = element_text(size = 26, face = "bold")) +
  theme(plot.title = element_text(size = 26,face = "bold"))






ggplot(TaskStackLiverTask, aes(ind, Subsys, fill= cut(-values,breaks = seq(from = 2.5, to = -2.5, length.out = 12), labels = seq(from = 2.5, to = -2.5, length.out = 11)))) + 
  geom_tile() +scale_x_discrete(labels=rep("-", nrow(Names)))+
  scale_fill_manual(drop = F, values = c("#700101","#e60202","#f06b6b","#f8b8b8","#fbd5d5","white","#c1c6f8","#949cf3","#606ced","#0013e3","#010a6e"), name = "Task Score")+
  theme(axis.text.x = element_text(size = 10, face = "bold")) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  theme(axis.title.x=element_blank(),axis.ticks = element_blank()) +
  theme(legend.key.size = unit(.5, 'cm'), #change legend key size
        legend.key.height = unit(.5, 'cm'), #change legend key height
        legend.key.width = unit(.5, 'cm'), #change legend key width
        legend.title = element_text(size=14, face= "bold"), #change legend title font size
        legend.text = element_text(size=10, face = "bold")) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank()) + xlab("Drugs") + theme(axis.title.y = element_text(size = 20, face = "bold")) 



ggplot(TaskStackLipidTask, aes(ind, Subsys, fill= cut(-values,breaks = seq(from = 2.5, to = -2.5, length.out = 12), labels = seq(from = 2.5, to = -2.5, length.out = 11)))) + 
  geom_tile() +scale_x_discrete(labels=rep("-", nrow(Names)))+
  scale_fill_manual(drop = F, values = c("#700101","#e60202","#f06b6b","#f8b8b8","#fbd5d5","white","#c1c6f8","#949cf3","#606ced","#0013e3","#010a6e"), name = "Task Score")+
  theme(axis.text.x = element_text(size = 10, face = "bold")) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  theme(axis.title.x=element_blank(),axis.ticks = element_blank()) +
  theme(legend.key.size = unit(.5, 'cm'), #change legend key size
        legend.key.height = unit(.5, 'cm'), #change legend key height
        legend.key.width = unit(.5, 'cm'), #change legend key width
        legend.title = element_text(size=14, face= "bold"), #change legend title font size
        legend.text = element_text(size=10, face = "bold")) +#change legend text font size
  theme(legend.title.align = 0.5,
        legend.direction = "vertical",
        legend.box.just = "center")+
  theme(panel.border = element_blank())+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(panel.background = element_blank()) + xlab("\n\n\nDrugs") + theme(axis.title.y = element_text(size = 20, face = "bold")) 

```







