---
title: "Liver DEGs Bonnie"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```



```{r Load}
# Written by Bonnie Dougherty, 2019-10-02
# Adapted by Connor Moore 2022-02-2

library(dplyr)
library(tidyr)
library(VennDiagram)
library(xlsx)

#source("http://www.bioconductor.org/biocLite.R")
#biocLite("GEOquery")
#biocLite("ALL")
#biocLite("Biobase")

#if (!requireNamespace("BiocManager", quietly = TRUE))
#  install.packages("BiocManager")
#BiocManager::install("genefilter")

library(GEOquery)
library(limma)
library(ggplot2)


############################## GSE130991 #########################################################################
# Download all data
# Returns a list of expression sets
gse_data <- getGEO("GSE130991", GSEMatrix = TRUE)

# Returns list of expression sets, only 1 entry
gse_data <- gse_data[[1]]



# Boxplot of values to make sure things are normalized correctly
boxplot(exprs(gse_data))

```

```{r Analyze}

gse_data$gender = gse_data$`gender:ch1`

gender_state <- data.frame(gse_data$gender) %>% 
  mutate(Male = grepl("Male", gse_data.gender), 
         Female = grepl("Female", gse_data.gender)) %>% 
  mutate(Summary = ifelse(Male == TRUE, "Male", ifelse(Female == TRUE, "Female", "")))

design <- model.matrix(~0 + factor(gender_state$Summary))
colnames(design) <- c("Male","Female")
contrast.matrix <- makeContrasts(Male - Female, levels = design)


gset <- getGEO("GSE130991", GSEMatrix =TRUE, getGPL=FALSE)
if (length(gset) > 1) idx <- grep("GPL20265", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

mart <- useMart("ENSEMBL_MART_ENSEMBL")
mart <- useDataset("hsapiens_gene_ensembl", mart)
annotLookup <- getBM(
  mart=mart,
  attributes=c(
    "affy_hta_2_0",
    "ensembl_gene_id",
    "gene_biotype",
    "external_gene_name"),
  filter = "affy_hta_2_0",
  values = gsub("hg.1", "hg", rownames(exprs(gset))), uniqueRows=TRUE)



# Previous research has indicated that filtering data to top 50% most variable genes increases power
library(genefilter)
gse_data_filter <- varFilter(gse_data)

gene.data <- annotLookup
colnames(gene.data) <- c('ID','ENSEMBL', 'GENETYPE','GENENAME')
gene.data <- gene.data %>% 
  filter(ENSEMBL != "NA")



# Run limma analysis
gse.data.process <- getEAWP(gse_data_filter)
lmfit <- lmFit(exprs(gse_data_filter), design)
# Run contrasts
lmfit.cont <- contrasts.fit(lmfit, contrast.matrix)
# Apply empirical Bayes
lmfit.cont.ebayes <- eBayes(lmfit.cont)
lmfit.cont.ebayes$genes <- gse.data.process$probes$ID

# Collect logFCs for saving to file
testResults <- topTable(lmfit.cont.ebayes, number = nrow(lmfit.cont.ebayes))

# Adjust for multiple tests, save logFCs
# This data is still with transcripts not grouped to the gene level yet
lmfit.results <- data.frame(ID = gse.data.process$probes$ID, 
                            decideTests(lmfit.cont.ebayes, adjust.method = "fdr", p.value = 0.1))
colnames(lmfit.results) <- c('ID','Male/Female')

lmfit.results <- left_join(lmfit.results, testResults, by = c("ID" = "ID")) #%>% 
#  dplyr::select('ID', 'Male/Female')
#colnames(lmfit.results) <- c('ID', 'Male/Female')


all.results <- full_join(gene.data, lmfit.results)
all.results <- all.results %>% 
  filter(!(is.na(ENSEMBL))) %>%
  filter(!(is.na(`Male/Female`)))

# Group results
all.results <- all.results %>% 
  group_by(ENSEMBL) %>% 
  mutate(Male = ifelse(`Male/Female` < 0, 1, 0), 
         Female = ifelse(`Male/Female` > 0, 1, 0))

all.data <- all.results
colnames(all.data)[1] <- 'GENE.NAME'

all.data %>% group_by(Male) %>% dplyr::count()
all.data %>% group_by(Female) %>% dplyr::count()

write.table(all.data, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Degs/GSE130991_DEGs.csv", 
            col.names = TRUE, row.names = FALSE, sep = ",")

# Determine how many DEGs map to the model
genes_in_model <- openxlsx::read.xlsx("C:/Users/cmoor/Documents/Papin Lab/Human1/Human-GEM.xlsx", sheet = 4)

model.genes.data <- genes_in_model %>% 
  inner_join(all.data, by = c("NAME" = "ENSEMBL"))

model.genes.data = model.genes.data[,-c(1,3,4,5,7)]

write.table(model.genes.data, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Degs/Human1_GSE130991_DEGs.csv", 
            col.names = TRUE, row.names = FALSE, sep = ",")

model.genes.data %>% group_by(Male == 0) %>% dplyr::count()
model.genes.data %>% group_by(Female == 0) %>% dplyr::count()

```

```{r old}

# Original length
colnames(gene.data) = c("ID", "gene_assignment")
all.results <- full_join(gene.data, lmfit.results)
all.results <- all.results %>% 
  filter(!(is.na(gene_assignment))) %>%
  filter(!(ID == "---"))

idx = grep("///", all.results$gene_assignment)
idx2 = idx + 1

all.results = all.results[idx2,]
all.results = unique(all.results)

# Group results
all.results <- all.results %>% 
  group_by(gene_assignment) %>% 
  mutate(Male = ifelse(`Male/Female` < 0, 1, 0), 
         Female = ifelse(`Male/Female` > 0, 1, 0))

all.data <- all.results
colnames(all.data)[1] <- 'GENE.NAME'

all.data %>% group_by(Male) %>% dplyr::count()
all.data %>% group_by(Female) %>% dplyr::count()

#write.table(all.data, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Degs/GSE130991_DEGs.csv", 
#            col.names = TRUE, row.names = FALSE, sep = ",")

# Determine how many DEGs map to the model
genes_in_model <- openxlsx::read.xlsx("C:/Users/cmoor/Documents/Papin Lab/Human1/Human-GEM.xlsx", sheet = 4) %>%
  dplyr::select(c(MIRIAM, NAME))
genes_in_model <- data.frame(sapply(genes_in_model, function(x) gsub("\'", "", x)))
colnames(genes_in_model) <- c('GENE.NAME', "ENSEMBL")

```

```{r genes}
FilteredGPL = read.table(file = 'C:/Users/cmoor/Documents/Papin Lab/Human1/Probeset/FilteredGPL.csv', sep = ',', header = TRUE)


all.data$GENE.NAME = gsub("hg.1", "hg",all.data$GENE.NAME)

colnames(FilteredGPL) = c("Idx","ENSEMBL", "GENE.NAME")
DEGswithNA = full_join(all.data, FilteredGPL)


DEGswithNA2 = DEGswithNA[!is.na(DEGswithNA$ENSEMBL),]
DEGswithNA3 = full_join(DEGswithNA2, genes_in_model, by ="ENSEMBL")
DEGswithNA3 = DEGswithNA3[!duplicated(DEGswithNA3$ENSEMBL),]
DEGswithNA3$logFC[DEGswithNA3$Male == 0 & DEGswithNA3$Female == 0] = 0
DEGswithNA3$logFC[is.na(DEGswithNA3$logFC)] = 0


DEGs = DEGswithNA3[!duplicated(DEGswithNA3$ENSEMBL),]
DEGs = DEGs[-c(2,12,14)]



write.table(DEGs, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Degs/Human1_DEGs.csv", 
            col.names = TRUE, row.names = FALSE, sep = ",")
```

```{r next}
model.genes.data = data.frame(matrix(0, nrow = nrow(all.data), ncol = 5))

counter = 1
for(i in 1:length(all.data$gene_assignment)){
  
  if(length(grep(all.data$gene_assignment[i], genes_in_model$GENE.NAME)) != 0){
    
    model.genes.data[counter,] = all.data[i,]
    counter = counter + 1

    
  }
  
  
}

colnames(model.genes.data) = colnames(all.data)
colnames(model.genes.data)[6] = "ENSEMBL"

#write.table(model.genes.data, file = "C:/Users/cmoor/Documents/Papin Lab/Human1/Degs/Human1_DEGs.csv", 
#            col.names = TRUE, row.names = FALSE, sep = ",")


model.genes.data %>% group_by(Male == 0) %>% dplyr::count()
model.genes.data %>% group_by(Female == 0) %>% dplyr::count()
```




